// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $countdown from "./routes/countdown.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $index_old from "./routes/index__old.tsx";
import * as $instance_domain_ from "./routes/instance/[domain].tsx";
import * as $AppRegister from "./islands/AppRegister.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $IdentityInput_old from "./islands/IdentityInput__old.tsx";
import * as $InfoLogger from "./islands/InfoLogger.tsx";
import * as $LoginIsland from "./islands/LoginIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/countdown.tsx": $countdown,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/index__old.tsx": $index_old,
    "./routes/instance/[domain].tsx": $instance_domain_,
  },
  islands: {
    "./islands/AppRegister.tsx": $AppRegister,
    "./islands/Countdown.tsx": $Countdown,
    "./islands/Counter.tsx": $Counter,
    "./islands/IdentityInput__old.tsx": $IdentityInput_old,
    "./islands/InfoLogger.tsx": $InfoLogger,
    "./islands/LoginIsland.tsx": $LoginIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
