// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $instance_domain_username_index from "./routes/instance/[domain]/[username]/index.tsx";
import * as $instance_domain_index from "./routes/instance/[domain]/index.tsx";
import * as $login_legacy_index from "./routes/login-legacy/index.tsx";
import * as $lookup_domain_username_index from "./routes/lookup/[domain]/[username]/index.tsx";
import * as $lookup_domain_index from "./routes/lookup/[domain]/index.tsx";
import * as $InfoLogger from "./islands/InfoLogger.tsx";
import * as $LoginIsland from "./islands/LoginIsland.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $TestIsland from "./islands/TestIsland.tsx";
import * as $UserDisplay from "./islands/UserDisplay.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/instance/[domain]/[username]/index.tsx":
      $instance_domain_username_index,
    "./routes/instance/[domain]/index.tsx": $instance_domain_index,
    "./routes/login-legacy/index.tsx": $login_legacy_index,
    "./routes/lookup/[domain]/[username]/index.tsx":
      $lookup_domain_username_index,
    "./routes/lookup/[domain]/index.tsx": $lookup_domain_index,
  },
  islands: {
    "./islands/InfoLogger.tsx": $InfoLogger,
    "./islands/LoginIsland.tsx": $LoginIsland,
    "./islands/Main.tsx": $Main,
    "./islands/TestIsland.tsx": $TestIsland,
    "./islands/UserDisplay.tsx": $UserDisplay,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
