// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $auth from "./routes/auth.tsx";
import * as $create_app from "./routes/create-app.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $AccessTokenCreate from "./islands/AccessTokenCreate.tsx";
import * as $AppCreate from "./islands/AppCreate.tsx";
import * as $UserCheck from "./islands/UserCheck.tsx";
import * as $UserLogin from "./islands/UserLogin.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/auth.tsx": $auth,
    "./routes/create-app.tsx": $create_app,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/AccessTokenCreate.tsx": $AccessTokenCreate,
    "./islands/AppCreate.tsx": $AppCreate,
    "./islands/UserCheck.tsx": $UserCheck,
    "./islands/UserLogin.tsx": $UserLogin,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
